"""Build the separate Codex plugin from the canonical Claude Code ruleset.

Uses only the Python standard library. Writes inside the checkout; never
installs the plugin or changes either host's configuration.
"""

import argparse
import json
import sys
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "codex" / "concise"


def json_bytes(value):
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf8")


def generated_files():
    source = (ROOT / "skills/concise/SKILL.md").read_text(encoding="utf8")
    # Only host-specific activation syntax changes; the ten rules stay canonical.
    body = source.split("\n---\n", 1)[1].lstrip("\n")
    body = body.replace("/concise:off", "$concise:concise-off")
    skill = """---
name: concise
description: 'Use when the user explicitly asks for concise mode or invokes $concise:concise. Apply concise, structured responses until $concise:concise-off or "stop concise mode".'
license: MIT
---

<!-- Generated by scripts/build_codex.py; edit skills/concise/SKILL.md at the repository root. -->

""" + body
    off = """---
name: concise-off
description: 'Use when the user invokes $concise:concise-off or asks to stop concise mode and return to the default response style.'
license: MIT
---

Stop applying the concise ruleset in this conversation. Confirm in one line,
then return to the default response style, following all other applicable
instructions. Do not change files, plugin installation, or configuration.
"""
    original = json.loads((ROOT / ".claude-plugin/plugin.json").read_text(encoding="utf8"))
    identity = {key: original[key] for key in ("name", "version", "author", "homepage", "repository", "license")}
    identity["description"] = "Structured, concise answers in Codex: answer first, numbered steps, and no filler. Activate explicitly with $concise:concise."
    identity["keywords"] = ["concise", "output-style", "structured-output", "productivity", "codex"]
    interface = {
        "displayName": "Concise",
        "shortDescription": "Clear answers, less scrolling",
        "longDescription": "Apply ten presentation rules with $concise:concise. Use $concise:concise-off to return to the default style. No tools, hooks, or persistent settings.",
        "developerName": original["author"]["name"],
        "category": "Productivity",
        "capabilities": ["Interactive"],
        "websiteURL": original["homepage"],
        "defaultPrompt": "Use $concise:concise for this conversation.",
        "logo": "./assets/logo.svg",
        "composerIcon": "./assets/logo.svg",
    }
    portable = {
        "$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",
        **identity,
        "extensions": {"com.openai": {"interface": interface}},
    }
    native = {**identity, "skills": "./skills/", "interface": interface}
    metadata = """interface:
  display_name: "{display}"
  short_description: "{description}"
  default_prompt: "{prompt}"
policy:
  allow_implicit_invocation: false
"""
    return {
        "plugin.json": json_bytes(portable),
        ".codex-plugin/plugin.json": json_bytes(native),
        "skills/concise/SKILL.md": skill.encode("utf8"),
        "skills/concise/agents/openai.yaml": metadata.format(
            display="Concise", description="Clear answers with no filler",
            prompt="Use $concise:concise for this conversation.",
        ).encode("utf8"),
        "skills/concise-off/SKILL.md": off.encode("utf8"),
        "skills/concise-off/agents/openai.yaml": metadata.format(
            display="Stop concise mode", description="Return to the default response style",
            prompt="Use $concise:concise-off to stop concise mode.",
        ).encode("utf8"),
        "README.md": (ROOT / "codex/README.md").read_text(encoding="utf8").encode("utf8"),
        "LICENSE": (ROOT / "LICENSE").read_text(encoding="utf8").encode("utf8"),
        "assets/logo.svg": (ROOT / "logo.svg").read_text(encoding="utf8").encode("utf8"),
    }


def stale_files(package, files):
    return [name for name, content in files.items()
            if not (package / name).is_file() or (package / name).read_bytes() != content]


def write_archive(package, archive):
    archive.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        for path in sorted(package.rglob("*")):
            if path.is_symlink():
                raise ValueError(f"Symlinks are not supported: {path}")
            if path.is_file():
                # Stable timestamps and permissions make repeat builds identical.
                info = zipfile.ZipInfo(package.name + "/" + path.relative_to(package).as_posix())
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = 0o100644 << 16
                bundle.writestr(info, path.read_bytes())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated files without writing")
    args = parser.parse_args()
    files = generated_files()
    extras = {p.relative_to(PACKAGE).as_posix() for p in PACKAGE.rglob("*") if p.is_file()} - files.keys()
    if extras:
        print("Unexpected package files: " + ", ".join(sorted(extras)), file=sys.stderr)
        return 1
    if args.check:
        stale = stale_files(PACKAGE, files)
        if stale:
            print("Stale Codex files: " + ", ".join(stale), file=sys.stderr)
            print("Run: python scripts/build_codex.py", file=sys.stderr)
            return 1
        print("Codex package is up to date.")
        return 0
    for name, content in files.items():
        path = PACKAGE / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    version = json.loads(files["plugin.json"])["version"]
    archive = ROOT / "dist" / f"concise-codex-{version}.zip"
    write_archive(PACKAGE, archive)
    print(f"Built {archive.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
