#!/usr/bin/env python3
"""Generate the Claude Code output style from the canonical ruleset.

`output-styles/concise.md` lets a user keep concise on per project through
Claude Code's own `/output-style concise:concise`, with no hook and no flag
file. The ruleset body is copied from skills/concise/SKILL.md so the two never
drift; `--check` fails when the generated file is stale.
"""

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "skills" / "concise" / "SKILL.md"
TARGET = ROOT / "output-styles" / "concise.md"

FRONTMATTER = """---
name: concise
description: Structured, concise answers - answer first, length matched to the task, no filler. Persists per project; keeps Claude Code's coding instructions.
keep-coding-instructions: true
---

<!-- Generated by scripts/build_output_style.py; edit skills/concise/SKILL.md instead. -->

"""


def generated_text():
    source = SOURCE.read_text(encoding="utf8").replace("\r\n", "\n")
    body = source.split("\n---\n", 1)[1].lstrip("\n")
    # The credit footer is for people reading the skill file, not the model.
    body = body.rsplit("\n---\n", 1)[0].rstrip("\n") + "\n"
    body = body.replace(
        "The ruleset specifies how you write; your responses stay ordinary prose and Markdown.",
        "The ruleset specifies how you write; your responses stay ordinary prose and Markdown. "
        "It is active as the selected output style; /output-style default turns it off.",
    )
    return FRONTMATTER + body


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check the generated file without writing")
    args = parser.parse_args()
    text = generated_text()
    if args.check:
        current = TARGET.read_text(encoding="utf8").replace("\r\n", "\n") if TARGET.is_file() else None
        if current != text:
            print(f"Stale {TARGET.relative_to(ROOT).as_posix()}. Run: python scripts/build_output_style.py", file=sys.stderr)
            return 1
        print("Output style is up to date.")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf8", newline="\n")
    print(f"Wrote {TARGET.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
